name: ~cb-project-name~
description: ~cb-project-description~

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_feathersjs: ^4.1.3
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  logger: ^1.3.0
  moment_dart: ^1.1.0
  rename: ^2.1.1
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "vx-index"

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
  assets:
    - assets/images/
